config/routes.rb
Hoopy::Application.routes.draw do

  get 'landing' => 'betatesters#new'
  get 'landing_ok' => 'betatesters#ok'

  get 'admin' => 'admin#index'
  controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy   # HM: Hoopy Login (Pend: juntar con Omniauth)
  end

  scope '(:locale)' do
   match "/signout" => "sessions#destroy", :as => :signout
   get 'welcome' => 'users#welcome'  # HM: Revisar!!
   get 'store' => 'store#index'
   get 'ready' => 'orders#ready'
   get 'selectfriend' => 'orders#selectfriend'
   post 'selectfriend' => 'sessions#setfriend' # Guarda el "friend" en el hash de la sesión
   get 'shops' => 'store#shops'
   get 'allies' => 'allies#index'
   get 'tos' => 'static#tos'
   get 'privacy' => 'static#privacy'
   get 'contact' => 'static#contact'
   get 'about' => 'static#about'
   post 'deliver' => 'orders#confirmdelivery'
   resources :enterprises do
        resources :products
   end
   resources :orders do
     member do
        get 'userpreview'
        get 'dealerpreview'
     end
   end
   resources :users
   resources :line_items
   resources :carts
   resources :products
   resources :betatesters
   get 'landing' => 'betatesters#new'
   get 'landing_ok' => 'betatesters#ok'
   post 'contactform' => 'betatesters#contactform'
   root :to => 'betatesters#new', :as => 'landing'
  end

 match "/auth/:provider/callback" => "sessions#create_omniauth"
 
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
 has_many :orders
 belongs_to :enterprise
 #validates :name, :presence => true, :uniqueness => true

 validates :password, :confirmation => true
 attr_accessor :password_confirmation
 attr_reader :password

 #validate :password_must_be_present

 #after_create :create_hashed_id
 after_destroy :ensure_an_admin_remains
 #after_initialize :init
 #
 #   def init
 #     self.image_url  ||= 0.0           #will set the default value only if it's nil
 #     self.provider  ||= 0.0           #will set the default value only if it's nil
 #     self.address ||= build_address #let's you set a default association
 #   end
 before_save :default_values
 def default_values
   # Set default provider as "hoopy" to differentiate from FB & TW.
   self.provider ||= 'hoopy'
 end

##### Para OMNIAUTH #####
def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    #user.name = auth["info"]["nickname"]
    user.nickname = auth["info"]["nickname"]
    user.name = auth["info"]["name"]
    user.email = auth["info"]["email"]
    user.image_url = auth["info"]["image"]
    user.location = auth["info"]["location"]
    user.description = auth["info"]["description"]
    user.fbtoken = auth["credentials"]["token"]
  end
end
#####################

 def ensure_an_admin_remains
	if User.count.zero?
	  raise "Can't delete last user"
	end
 end

 def User.authenticate(nickname, password)
        #if user = find_by_name(name) 
        if user = find_by_nickname_and_provider(nickname, "hoopy") 
           if user.hashed_password == encrypt_password(password, user.salt)
                user
           end
        end
 end

 def User.encrypt_password(password, salt)
   Digest::SHA2.hexdigest(password + "wibble" + salt)
 end

# 'password' is a virtual attribute
 def password=(password)
        @password = password

        if password.present?
           generate_salt
           self.hashed_password = self.class.encrypt_password(password, salt)
        end
 end


private

  def password_must_be_present
   errors.add(:password, "Missing password") unless hashed_password.present?
  end

  def generate_salt
   self.salt = self.object_id.to_s + rand.to_s
  end

 #private
 # def self.hash_password(password)
 #	Digest::SHA1.hexdigest(password)
 # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:nickname)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  def welcome
    #@user = User.find(params[:id])

    #### Gifts to redeem
    # Gifts to redeem TWITTER: (nickname, provider)
    @orders = Order.where(:beneficiary => current_user.nickname, :provider_type => current_user.provider, :okshop_at => nil).paginate :page => params[:page], :order=> 'created_at DESC', :per_page => 20
    # Gifts to redeem FACEBOOK: (uid, provider)
    # @orders = Order.where(:beneficiary_uid => current_user.uid, :provider_type => current_user.provider, :okshop_at => nil).paginate :page => params[:page], :order=> 'created_at DESC', :per_page => 20

    @orders_sent = Order.where(:user_id => current_user.id).paginate :page => params[:page], :order=> 'created_at DESC', :per_page => 20

    #### Redeemed gifts
    # Redeemed gifts TWITTER:
    @orders_picked = Order.where(:beneficiary => current_user.nickname, :provider_type => current_user.provider).paginate :page => params[:page], :order=> 'created_at DESC', :per_page => 20
    # Redeemed gifts FACEBOOK:
    # @orders_picked = Order.where(:beneficiary_uid => current_user.uid, :provider_type => current_user.provider, :okshop_at => !nil).paginate :page => params[:page], :order=> 'created_at DESC', :per_page => 20

    ### All gifts
    # TWITTER:
    @orders_all = Order.where("(beneficiary = ? AND provider_type = ?) OR (user_id = ?)", current_user.nickname, current_user.provider, current_user.id).paginate :page => params[:page], :order=> 'created_at DESC', :per_page => 20

    @total_orders = Order.count 
    @shop_orders_pending = Order.where(:enterprise_id => current_user.enterprise_id, :okshop_at => nil)
    @shop_orders_delivered = Order.where(:enterprise_id => current_user.enterprise_id)
    respond_to do |format|
      format.html # welcome.html.erb
      format.json { render :json => @user }
    end
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        #format.html { redirect_to @user, :notice => 'User #{@user.name} was successfully created.' }
        format.html { redirect_to(users_url, :notice => "User #{@user.nickname} was successfully created.") }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url, :notice => "User #{@user.nickname} was successfully updated.") }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
     @user.destroy
     flash[:notice] = "User #{@user.nickname} deleted"
    rescue Exception => e
     flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_customerview.html.erb
<p class="center"><%=t('.msgtopick')%> <strong><%= pluralize(@orders.count, t('.regalo')) %></strong>.</p>
<br />

<div class="tabbable tabs-top">
 <ul class="nav nav-tabs">
   <li class="active">
	<a data-toggle="tab" href="#lA"><%=t('.recvs')%></a>
   </li>
   <li class="">
	<a data-toggle="tab" href="#lB"><%=t('.sent')%></a>
   </li>
   <li class="">
	<a data-toggle="tab" href="#lC"><%=t('.allrecvs')%></a>
   </li>
 </ul>
<div class="tab-content">
 <div id="lA" class="tab-pane active">
        <ul class="thumbnails">	  
	    <% @orders.each do |order| %>
            <li>
             <div class="thumbnail">
		 <% if order.okshop_at.nil? %>
			 <span class="label label-info"><%=t('.from')%>:</span> <%= order.user.name %><br />
			 <%= link_to image_tag("/images/gift-closed-ico.png", :width => 64, :height => 64, :class => "shopbut"), userpreview_order_path(order) %>
		 <% else %>
			 <%= link_to image_tag("/images/gift-open-ico.png", :width => 64, :height => 64, :class => "padbut"), userpreview_order_path(order) %>
		 <% end %>
		 <small><%order.id%></small>
             </div>
            </li>
	    <% end %>
        </ul>
	    <p><%= will_paginate @orders %></p>
 </div>
 <div id="lB" class="tab-pane">
	<ul class="thumbnails">
	   <% @orders_sent.each do |sent| %>
	    <li>
	     <div class="thumbnail">
		<% if sent.okshop_at.nil? %>
                        <span class="label label-info"><%=t('.to')%>:</span> <%= sent.beneficiary %><br />
			<%= link_to image_tag("/images/gift-closed-ico.png", :width => 64, :height => 64, :class => "shopbut"), userpreview_order_path(sent) %>
		<% else %>
			<%= link_to image_tag("/images/gift-open-ico.png", :width => 64, :height => 64, :class => "padbut"), userpreview_order_path(sent) %>
		<% end %>
                 <small><%sent.id%></small>
	     </div>
	    </li>
	   <% end %>
	</ul>
	   <p><%= will_paginate @orders_sent %></p>
 </div>
 <div id="lC" class="tab-pane">
        <ul class="thumbnails">
	 <% @orders_all.each do |rec| %>
            <li>
             <div class="thumbnail">
		<% if rec.okshop_at.nil? %>
			<span class="label label-info"><%=t('.from')%>:</span> <%= rec.user.name %><br />
			<%= link_to image_tag("/images/gift-closed-ico.png", :width => 64, :height => 64, :class => "shopbut"), userpreview_order_path(rec) %>
		<% else %>
			<%= link_to image_tag("/images/gift-open-ico.png", :width => 64, :height => 64, :class => "shopbut"), userpreview_order_path(rec) %>
		<% end %>
                 <small><%rec.id%></small>
             </div>
            </li>
	 <% end %>
        </ul>
	  <p><%= will_paginate @orders_all %></p>
 </div>
</div>
</div>


app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <fieldset>
   <legend>Enter User Details</legend>
    <div>
    <%= f.label :nickname, 'Hoopy Nickname' %>
    <%= f.text_field :nickname, :size => 40 %>
    </div>
    <div>
    <%= f.label :name, 'Full name' %>
    <%= f.text_field :name, :size => 40 %>
    </div>
    <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url, :size => 40 %>
    </div>
    <div>
    <%= f.label :email %>
    <%= f.text_field :email, :size => 40 %>
    </div>
    <div>
    <%= f.label :provider %>
    <%= f.text_field :provider, :size => 40 %>
    </div>
    <div>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password, :size => 40 %>
    </div>
    <div>
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation, :size => 40 %>
    </div>
    <div>
    <%= f.submit %>
    </div>
 </fieldset>
<% end %>
</div>

app/views/users/_shopview.html.erb
<% current_user.name.capitalize %>

<div id="box">
 <h3><%=t('.pending')%></h3>
 <% @shop_orders_pending.each do |rec| %>
  <div class="entry" >
        <% if rec.okshop_at.nil? %>
                <%= link_to image_tag("/images/gift-closed-ico.png", :width => 64, :height => 64, :class => "picgift"), dealerpreview_order_path(rec) %>
        <% else %>
                <%= link_to image_tag("/images/gift-open-ico.png", :width => 64, :height => 64, :class => "picgift"), dealerpreview_order_path(rec) %>
        <% end %>
     <br /><span class="label label-info"><%=t('.to')%>:</span> 
	<% if rec.provider_type == "twitter" %><a href="https://twitter.com/<%= rec.beneficiary %>">@<%= rec.beneficiary %></a><%else%><%= rec.beneficiary %><%end%>
	<span class="lastupdate">(<%= distance_of_time_in_words(Time.now, rec.created_at, true) %> <%=t('.ago')%>)</span>

     <br /><span class="label label-info"><%=t('.buy_date')%>:</span> <%= rec.created_at.strftime("%d %b %Y - %I:%M:%S %p") %> 
  </div>
  <br />
 <% end %>
</div>
<hr>

<div id="box">
 <h3><%=t('.all')%></h3>
 <% @shop_orders_delivered.each do |del| %>
  <div class="entry" >
        <% if del.okshop_at.nil? %>
                <%= link_to image_tag("/images/gift-closed-ico.png", :width => 64, :height => 64, :class => "picgift"), dealerpreview_order_path(del) %>
        <% else %>
                <%= link_to image_tag("/images/gift-open-ico.png", :width => 64, :height => 64, :class => "picgift"), dealerpreview_order_path(del) %>
        <% end %>
     <br /><span class="label label-info"><%=t('.to')%>:</span> 
        <%# Show @ for twitter accounts %>
	<% if del.provider_type == "twitter" %><a href="https://twitter.com/<%= del.beneficiary %>">@<%= del.beneficiary %></a><%else%><%= del.beneficiary %><%end%>
	<span class="lastupdate">(<%= distance_of_time_in_words(Time.now, del.created_at, true) %> <%=t('.ago')%>)</span    > 

     <br /><span class="label label-info"><%=t('.buy_date')%>:</span> <%= del.created_at.strftime("%d %b %Y - %I:%M:%S %p") %> 
  </div>
  <br />
 <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div id="product_list">
<h1>Listing users</h1>

  <% if notice %>
	<p id="notice"><%= notice %></p>
  <% end %>


<table class="table table-striped table-hover">
<% @users.each do |user| %>
  <tr>
    <td><%= image_tag(user.image_url, :width => 50, :height => 50) %>
        <%= user.id %>
    </td>
    <td>
	<b>UID:</b> <%= user.uid %> <br />
	<b>Nickname:</b> <%= user.nickname %> <br />
	<b>Name:</b> <%= user.name %> <br />
	<b>Hashed password:</b> <%= user.hashed_password %> <br />
	<b>Salt:</b> <%= user.salt %>  <br />
	<b>E-mail:</b> <%= user.email %>  <br />
	<b>Provider:</b> <%= user.provider %>  <br />
	<b>Created:</b> <%= user.created_at %>  <br />
	<b>Updated:</b> <%= user.updated_at %>  
    </td>
    <td><%= link_to image_tag("/images/ico-about.png", :width => 16, :height => 16), user %> <br />
        <%= link_to image_tag("/images/ico_pencil.gif", :width => 16, :height => 16), edit_user_path(user) %><br />
        <%= link_to image_tag("/images/ico_dialog-close.png", :width => 16, :height => 16), user, :method => :delete, :confirm => 'Are you sure?' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if notice %>
 <p id="notice" ><%= notice %></p>
<% end %>

<p><%= image_tag(@user.image_url, :width => 50, :height => 50) %></p
<p><b>ID:</b> <%= @user.id %></p>
<p><b>UID:</b> <%= @user.uid %></p>
<p><b>Nickname:</b> <%= @user.nickname %></p>
<p><b>Name:</b> <%= @user.name %></p>
<p><b>Hashed password:</b> <%= @user.hashed_password %></p>
<p><b>Salt:</b> <%= @user.salt %></p>
<p><b>E-mail:</b> <%= @user.email %></p>
<p><b>Provider:</b> <%= @user.provider %></p>
<p><b>Location:</b> <%= @user.location %></p>
<p><b>Description:</b> <%= @user.description %></p>
<p><b>Created:</b> <%= @user.created_at %></p>
<p><b>Updated:</b> <%= @user.updated_at %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/welcome.html.erb
 <%= image_tag(current_user.image_url, :id => 'avatar', :width => 50, :height => 50) %>
 <h2 class="center"><%=t('.bienvenido')%></h2>
 <span class="label"><%= current_user.name.upcase %></span>
 <% debug(current_user.uid) if Rails.env.development? %>
 <hr>

                <% if notice %>
                 <div class="alert alert-success" ><%= notice %>
                    <button data-dismiss="alert" class="close" type="button">x</button>
                 </div>
                <% end %>

                <% if alert %>
                 <div class="alert alert-error" ><%= alert %>
                    <button data-dismiss="alert" class="close" type="button">x</button>
                 </div>
                <% end %>


<% if current_user.type_id == 2 %>
	<%= render 'shopview' %>
<% end %>

<% if current_user.type_id.nil? %>
        <%= render 'customerview' %>
<% end %>

<% if current_user.type_id == 1 %>
        <%= render 'customerview' %>
<% end %>