config/routes.rb
Hoopy::Application.routes.draw do

  get 'landing' => 'betatesters#new'
  get 'landing_ok' => 'betatesters#ok'

  get 'admin' => 'admin#index'
  controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy   # HM: Hoopy Login (Pend: juntar con Omniauth)
  end

  scope '(:locale)' do
   match "/signout" => "sessions#destroy", :as => :signout
   get 'welcome' => 'users#welcome'  # HM: Revisar!!
   get 'store' => 'store#index'
   get 'ready' => 'orders#ready'
   get 'selectfriend' => 'orders#selectfriend'
   post 'selectfriend' => 'sessions#setfriend' # Guarda el "friend" en el hash de la sesión
   get 'shops' => 'store#shops'
   get 'allies' => 'allies#index'
   get 'tos' => 'static#tos'
   get 'privacy' => 'static#privacy'
   get 'contact' => 'static#contact'
   get 'about' => 'static#about'
   post 'deliver' => 'orders#confirmdelivery'
   resources :enterprises do
        resources :products
   end
   resources :orders do
     member do
        get 'userpreview'
        get 'dealerpreview'
     end
   end
   resources :users
   resources :line_items
   resources :carts
   resources :products
   resources :betatesters
   get 'landing' => 'betatesters#new'
   get 'landing_ok' => 'betatesters#ok'
   post 'contactform' => 'betatesters#contactform'
   root :to => 'betatesters#new', :as => 'landing'
  end

 match "/auth/:provider/callback" => "sessions#create_omniauth"
 
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :enterprise
  belongs_to :user

   PAYMENT_TYPES = [ "Credit card", "Gift Card", "SafetyPay", "Tarjeta pre-pago", "Hoopy Points"]
   #PROVIDER_TYPES = [ "hoopy", "twitter", "facebook" ]
   PROVIDER_TYPES = [ "hoopy", "twitter", "facebook" ]

   #validates :name, :faceadd, :msg, :email, :pay_type, :presence => true
   validates :beneficiary, :pay_type, :presence => true # :msg, :email,   <- Making the Email notification optional for now ;-)
   validates :pay_type, :inclusion => PAYMENT_TYPES
   validates :provider_type, :inclusion => PROVIDER_TYPES

   after_create :create_hashed_id

   def to_param
     self.hashed_id
   end

   def add_line_items_from_cart(cart)
     cart.line_items.each do |item|
	item.cart_id = nil
	line_items << item
     end
   end

   def set_enterprise_owner(cart)
     self.update_attributes(:enterprise_id => cart.line_items.first.product.enterprise_id)
        #Cart.last.line_items.first.product.enterprise_id
   end

private
   def create_hashed_id
     self.update_attributes(:hashed_id => Digest::SHA2.hexdigest([Time.now, rand].join)[0,64])
   end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 #TODO: Restringir acceso (Si se habilita la linea de abajo)
 #skip_before_filter :authorize

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    #@user = Orders.user rescue User.find(@orders.user_id)
    #@micropost = Micropost.find(params[:id])
    # Hack to handle Rails bug:
    #@user = Micropost.user rescue User.find(@micropost.user_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id])
    @user = Order.user rescue User.find(@order.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    # session:[friend] está en SessionsController 
    @sessionfriend = session[:friend]
    @sessionfriend_fb_name = session[:friend_fb_name]
    @sessionfriend_fb_num = session[:friend_fb_num]
    @cart = current_cart
    if @cart.line_items.empty?
	redirect_to allies_path, :notice => "Your cart is empty"
	return
    end

    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render :json => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    #@order = Order.new(params[:order])
    @order = current_user.orders.build(params[:order])
    @order.set_enterprise_owner(current_cart)
    @order.add_line_items_from_cart(current_cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
	## HM: Deshabilitado envío de correos para que funcione en Heroku!!
	## HM: Notifier.order_received(@order).deliver
        #format.html { redirect_to store_index_path, :notice => 'Orden creada. Gracias por usar Hoopy.' }
        format.html { redirect_to ready_path, :notice => I18n.t('.thanks') }
	#format.js
        format.json { render :json => @order, :status => :created, :location => @order }
      else
        format.html { render :action => "new" }
        format.json { render :json => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id])

    # Confirm the code matches:
    if (@order.codrecgift != params[:order][:codrecgift].to_i)
       flash[:alert] = "#{params[:order][:codrecgift]} #{t('msgs.confirmation_mismatch')}" 
       redirect_to welcome_path and return
    end

    respond_to do |format|
      if @order.update_attributes(params[:order])
        #format.html { redirect_to @order, :notice => 'Order was successfully updated.' }
        format.html { redirect_to dealerpreview_order_path(@order), :notice => "#{t('msgs.order_updated')}" }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :ok }
    end
  end

  def userpreview 
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id]) # Other TESTING: .where("beneficiary = ? OR beneficiary_uid = ?", current_user.nickname, current_user.uid)
    @user = Order.user rescue User.find(@order.user_id)
    #@url = "https://huupy.com/orders/#{@order.hashed_id}/dealerpreview"
    @url = "https://nameless-headland-1824.herokuapp.com/orders/#{@order.hashed_id}/dealerpreview?c=#{@order.codrecgift}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order }
    end
  end

  def dealerpreview
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id])
    @url = "https://huupy.com/orders/#{@order.hashed_id}/dealerpreview"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @order }
    end
  end
 
  def dealerconfirm
    #@order = Order.find(params[:id])
    @order = Order.find_by_hashed_id(params[:id])
  end
 
  def confirmdelivery   # ????? 
    @order = Order.find_by_hashed_id(params[:hashed_id])
    respond_to do |format|
        if (@order.codrecgift.to_s() == params[:codrecgift])
                @order.update_attributes(:okshop_at => Time.now)
	  	#render :text => @order.hashed_id #params #params[:codrecgift] 
		format.html { redirect_to dealerpreview_order_path(@order), :notice => "#{t('msgs.order_updated')}" }
		format.json { head :ok }
	else
		#@order.codrecgift #{params[:codrecgift]}" #"No actualizado"
		format.html { redirect_to dealerpreview_order_path(@order), :notice => "#{t('msgs.confirmation_mismatch')}" }
		format.json { render :json => @order.errors, :status => :unprocessable_entity }
        end
    end
  end

  #def showavatar
  #  @avatar = "https://si0.twimg.com/profile_images/1239447061/Unnamed-1_reasonably_small.jpg"
  #end

  def ready
  end

  def selectfriend
        #if session[:friend].nil?
        #  @friend = ""
        #else
          #@friend = session[:friend]
          @friend ||= session[:friend] if session[:friend]
        #end
  end

  # def setfriend   <-- It's in SessionsController

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_fbfriendselector.html.erb
<p><%=t('.fbcomplete')%> :-) </p>

<div class="ui-widget">
        <%= text_field_tag :fbfriend_name, params[:fbfriend_name], :size => 26, :value => @friend, :autocomplete => 'off' %>
        <%= text_field_tag :fbfriend_num, params[:fbfriend_num], :size => 26, :type => 'hidden' %>
</div>

<p><a href="https://graph.facebook.com/me/friends?access_token=<%= current_user.fbtoken %>"></a></p>


  <script>
    $(function() {
	// http://jsfiddle.net/ZGmyp/	<- City example
	// http://jsfiddle.net/ALyse/   <- Hoopy sandbox FB-friends (update ACCESS-TOKEN)
	// http://jqueryui.com/demos/autocomplete/#custom-data
      $( "#fbfriend_name" ).autocomplete({
        source: function( request, response ) {
        $.ajax({
          url: "https://graph.facebook.com/me/friends?access_token=<%= current_user.fbtoken %>&callback=?",
          dataType: "jsonp",
          data: {
            featureClass: "P",
            style: "full",
            maxRows: 6,
            name_startsWith: request.term
          },
          success: function( data ) {
            res = $.map( data.data, function( item ) {
              if (item.name.toLowerCase().indexOf(request.term.toLowerCase()) >= 0){
                return {
                  label: item.name,
                  value: item.name,   // Quitar id, poner name.   id a form
                  idvalue: item.id
                }
              }
            });
            response(res);
          }
        });
      },
      minLength: 1,
      select: function( event, ui ) {
         console.log( ui.item ?
         "Selected: " + ui.item.label :
         "Nothing selected, input was " + this.value);
         $( "#fbfriend_num" ).val( ui.item.idvalue );
         //alert( item.uid );
         //return false;
      },
      open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
      },
      close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
      }
      });
//      .data("autocomplete")._renderItem = function( ul, item ) {
//          console.log(item);
	 // OJO: Para la foto: cambiar item.value => item.idvalue
//          var image_url = "http://graph.facebook.com/" + item.value +"/picture";
//          return $( "<li>" )
//            .append($("<img style='float:left'>").attr('src',image_url))
//            .append( $( "<a>" ).text( item.label ) )
          //.append( $( "<a>" ).text( item.value ) )
//            .appendTo( ul );
//      };
    });
    </script>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-block alert-error fade in" ><%= notice %>
      <button data-dismiss="alert" class="close" type="button">×</button>
	<h2><%= t('errors.template.header', :count=>@order.errors.size, :model=>t('activerecord.models.order')) %>.</h2>
	<p><%= t('errors.template.body') %></p>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= raw msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="avatar-order">
  <% image_tag('hoopypet-1color.png', :id => 'avatar', :width => 50, :height => 50) %>
  </div>

  <!-- Selec de RedSocial -->
 <% if current_user.fbtoken && current_user.provider == "facebook" %>
          <%= f.hidden_field :provider_type, :value => "facebook" %>
                <p><i class="icon-facebook-sign"></i> <%= @sessionfriend_fb_name %></p>
		<% debug(@sessionfriend_fb_num) if Rails.env.development? %>
          <%= f.hidden_field :beneficiary, :size => 26, :value => @sessionfriend_fb_name, :autocomplete => 'off' %>
          <%= f.hidden_field :beneficiary_uid, :size => 26, :value => @sessionfriend_fb_num, :autocomplete => 'off' %>
 <% else %>
 <% end %>

 <% if current_user.provider == "twitter" %>
		<p><i class="icon-twitter-sign"></i> @<%= @sessionfriend %></p>
	  <%= f.hidden_field :provider_type, :value => "twitter" %>
	  <%= f.hidden_field :beneficiary, :size => 26, :value => @sessionfriend, :autocomplete => 'off' %>
 <% else %>
 <% end %>

<% if current_user.provider == "hoopy" %>
                <p><i class="icon-gift"></i> <%= @sessionfriend %></p>
          <%= f.hidden_field :provider_type, :value => "hoopy" %>
          <%= f.hidden_field :beneficiary, :size => 26, :value => @sessionfriend %>
<% else %>
<% end %>
  <!-- Selec de RedSocial -->

  <div class="field">
    <%= f.label :email, t('.mailnotice') %>
    <%= f.text_field :email, :size => 20, :value => '' %>
  </div>
  <div class="field">
    <%= f.label :email, t('.message') %>
    <%= f.text_area :msg, :rows => 3, :cols => 30, :value => '' %>
  </div>
  <div class="field">
    <%= f.hidden_field :pay_type, :value => "Hoopy Points" %>
  </div>
  <div class="field">
    <%= f.hidden_field :codrecgift, :size => 20, :value => rand(1000000) %> 
  </div>
  <div class="actions">
    <%= f.submit t('.submit'), :class => "btn btn-large btn-success", :disable_with => t('.wait') %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<table>

 <%= render(order.line_items) %>

</table>

app/views/orders/create.js.erb
$('.selector').combobox({
        selected: function(event, ui) {
            alert('selected');
        },
        changed: function (event, ui) {
            alert('changed');
        }
    });
alert('Order!');
$(document).ready(function() {
    $("#order_provider_type").change(function() {
        var src2 = $(this).val();
        var src = "https://si0.twimg.com/profile_images/1239447061/Unnamed-1_reasonably_small.jpg";
        alert('OH!');

        $("#avatar-order").html(src ? "<img src='" + src + "'>" : "");
    });
});

app/views/orders/dealerpreview.html.erb
                <% if notice %>
                 <div class="alert alert-success" ><%= notice %>
                    <button data-dismiss="alert" class="close" type="button">x</button>
                 </div>
                <% end %>

                <% if alert %>
                 <div class="alert alert-error" ><%= alert %>
                    <button data-dismiss="alert" class="close" type="button">x</button>
                 </div>
                <% end %>


<div id="box">
 <h1><%=t('.order')%></h1>

  <div id="mensaje">
	<div class="right"> <%=t('.buy_date')%>: <%= @order.created_at.strftime("%d %b %Y - %I:%M:%S %p") %> </div>
	<p>
	        <% if @order.okshop_at.nil? %>
		  <div class="status-pend"><%=t('.ready_topick')%></div>
	        <% else %>
	          <div class="status-ok"><%=t('.delivered')%></div>
	        <% end %>
	  <br />
	</p>

	<%= render @order %>
        <br />
  </div>
        <br />

        <% if @order.okshop_at.nil? %>
		<h1><%=t('.info_to_deliver')%></h1>
		<p>
		   <strong><%=t('.codok_shop')%></strong>:
                   <%= form_for(@order) do |o| %>
                     <%= o.text_field :codrecgift, :size => 10, :value => params[:c] %>
                     <%= o.hidden_field :okshop_at, :value => Time.now %>
                     <%= o.submit t('.confirm_delivery'), :confirm => t('.sure') %>
                   <% end %>
                   <%# The form below is obsolete, but kept as possible reference %>
		   <% form_tag deliver_path(@order), :method => :post do %>
		     <%= text_field_tag :codrecgift, @order.codrecgift, :size => 10 %>
		     <%= hidden_field_tag :hashed_id, @order.hashed_id %>
		     <%= submit_tag t('.confirm_delivery') %>
		   <% end %>
		</p>
		<p>* <%=t('.confirm_notice')%></p>

        <% else %>
                        <div id="sticker-table">
                        <ul>
                                <li>
                                        <ul>
                                            <li class="r"><%=t('.shop_delivery')%></li>
                                        </ul>
                                        <ul>
                                            <li class="l"><%= @order.okshop_at %></li>
                                        </ul>
                                </li>
                                <li>
                                        <ul>
                                            <li class="r"><%=t('.client_confirmation')%></li>
                                        </ul>
                                        <ul>
                                            <li class="l"><%= @order.okuser_at %></li>
                                        </ul>
                                </li>
                        </ul>
                        </div>
        <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div id="product_list">
<h1>Listado de Pedidos</h1>

<table>
<% @orders.each do |order| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= order.id %></td>
    <td>
     <strong>Para (.name):</strong> <%= order.name %> [<%= order.provider_type %>] <br />
     <strong>De (.user_id):</strong> <%= order.user_id %> <br />
     <strong>Enterprise (.enterprise_id):</strong> <%= order.enterprise_id %> <br />
     <strong>Mensaje:</strong> <%= order.msg %> <br />
     <strong>e-mail:</strong> <%= order.email %> <br />
     <strong>CodRecGift:</strong> <%= order.codrecgift %> <br />
     <strong>Tipo de Pago:</strong> <%= order.pay_type %>
    </td>
    <td>
     <%= link_to image_tag("/images/ico-about.png", :width => 16, :height => 16), order %>
     <%= link_to image_tag("/images/ico_pencil.gif", :width => 16, :height => 16), edit_order_path(order) %>
     <%= link_to image_tag("/images/ico_dialog-close.png", :width => 16, :height => 16), order, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="row">
  <div class="span12 pagination-centered">

   <fieldset>
	<legend><%= t('.legend') %></legend>
	<%= render 'form' %>
   </fieldset>

  </div>
</div>

app/views/orders/ready.html.erb
<% if notice %>
 <div class="alert alert-block alert-success fade in" ><%= notice %>
    <button data-dismiss="alert" class="close" type="button">×</button>
 </div>
<% end %>

   <div class="row">
         <div class="span6 pagination-centered">
<p><a href="welcome" class="btn btn-large"><i class="icon-home"></i><%= t('.back_to_home') %></a></p>
        </div>
         <div class="span6 pagination-centered">
<p><a href="selectfriend" class="btn btn-large"><i class="icon-gift"></i><%= t('.send_another_gift') %></a></p>
	</div>
   </div>

app/views/orders/selectfriend.html.erb
<% if notice %>
 <div class="alert alert-block alert-success fade in" ><%= notice %>
    <button data-dismiss="alert" class="close" type="button">×</button>
 </div>
<% end %>

   <div class="row">
         <div class="span12 pagination-centered">

        <%= form_tag do %>
                <fieldset>
                        <legend><%= t('.legend') %></legend>

  <!-- Nueva Selec de RedSocial -->
				 <% if current_user.fbtoken && current_user.provider == "facebook" %>
				        <p><%= t('.select_friend') %> <span class="label label-info">Facebook</span></p>
					<%= render 'fbfriendselector' %>
				 <% else %>
				 <% end %>

				 <% if current_user.provider == "twitter" %>
					<div>
					<p><%= t('.select_friend') %> <span class="label label-info">Twitter</span></p>
					  <div class="field">
					    <div class="input-prepend">
					     <span class="add-on">@</span><%= text_field_tag :nickname, params[:nickname], :size => 26, :value => @friend, :autocomplete => 'off' %>
					    </div>
					  </div>
					</div>
				 <% else %>
				 <% end %>
  <!-- Nueva Selec de RedSocial -->
                                 <% if current_user.provider == "hoopy" %>
                                        <p><%= t('.select_friend') %> <span class="label label-info">Huupy</span></p>
                                          <div class="field">
                                            <div class="input-prepend">
                                             <%= text_field_tag :nickname, params[:nickname], :size => 26, :value => @friend, :autocomplete => 'off' %>
                                            </div>
                                          </div>
                                 <% else %>
                                 <% end %>

                        <div>
                                <%= submit_tag "Next", :class => "btn btn-success btn-large" %>
                        </div>
                </fieldset>
        <% end %>

        </div>
   </div>

app/views/orders/show.html.erb
<% if notice %>
 <p id="notice" ><%= notice %></p>
<% end %>

<h1>Datos de env&iacute;o</h1>

<div id="mensaje">
	<p>
	 <b>De:</b>
	  <%= @user.nickname.upcase %> en <%= @user.provider.capitalize %> <br />
	 <b>Para:</b>
	  <%= @order.name.upcase %> en <%= @order.provider_type.capitalize %> (<em><%= @order.email %></em>)
	</p>

	 <b>Forma de pago:</b>
	  <%= @order.pay_type %> <br />

  <div class="content">
        <p>
          Mensaje personalizado:<br />
          <%= @order.msg %>
        </p>
  </div>
</div>

<h1>Regalos enviados</h1>

<%= render @order %>

<p>
  Fecha de Compra: <%= @order.created_at %>
  <br />
  ¿Entregado?:
        <% if @order.okshop_at.nil? %>
         <strong>Pendiente</strong>
        <% else %>
         OK
        <% end %>
  <br />
  Conformidad del cliente:
        <% if @order.okuser_at.nil? %>
         <strong>Pendiente</strong>
        <% else %>
         OK
        <% end %>
</p>

        <% if current_user %>
        <% if current_user.type_id == 1 %>
		<p><%= link_to 'Ver cómo lo vera el destinatario', userpreview_order_path(@order) %></p>
		<p><%= link_to 'Ver cómo lo vera el establecimiento', dealerpreview_order_path(@order) %></p>
		<p><%= link_to 'Edit', edit_order_path(@order) %></p>
	<% end %>
	<% end %>

app/views/orders/userpreview.html.erb
<% if notice %>
 <p id="notice" ><%= notice %></p>
<% end %>

<div id="box">
 <h1><%= t('.for') %>: <strong><%= @order.beneficiary.upcase %></strong></h1>

 <div id="mensaje">
    <b><%=t('.from')%>:</b> <%= @user.nickname.upcase %> 
    <div class="right"> <%= @order.created_at.strftime("%d %b %Y - %I:%M:%S %p") %> </div>

    <div class="content"> 
    <%= @order.msg %>
    </div>

    <div class="gift">
      <%= render @order %>
    </div>

     <%= image_tag(@order.enterprise.logo_url)%>
 </div>
 <br />
 
    <%# THIS WORKS WITH TWITTER FOR NOW %>
    <%# Now We show the picking up info also to the Sender just in case! %>
    <%#if @order.provider_type == "Facebook" || @order.provider_type == "Twitter" %>
        <%# if @order.okuser_at.nil? && @order.beneficiary_uid.to_s() == current_user.uid %>
        <% if @order.okuser_at.nil? %>
		<h1><%=t('.info_to_pick')%></h1>
		<p>
		 1) <%=t('.info_1')%> <br />
		 2) <%=t('.info_2')%> <br />
		 3) <%=t('.info_3')%> 
		</p>
                <div id="mensaje">
                <% unless @order.okshop_at.nil? %>
                   <%= form_for(@order) do |o| %>
                     <%= o.hidden_field :okuser_at, :value => Time.now %>
                     <%= o.submit t('.recv_ok'), :confirm => t('.sure') %>
                   <% end %>
                <% end %>
                </div>
		<p id="notice">
		  <% image_tag("/images/code-bars.png") %>
		  <% image_tag("/images/code-qr.png", :width => 120, :height => 120) %>
		  <%= image_tag("https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl=#{@url}&choe=UTF-8") %>
		  <% image_tag("/images/code-mstag.jpg", :width => 120, :height => 120) %>   <br />
		  <%=t('.codok_shop')%>: <b><%= @order.codrecgift %></b>
                  <small><a href="<%=@url%>">direct link</a></small>
		</p>
        <% elsif @order.okshop_at.nil? %>
                <p><%=t('.shop_not_confirmed')%>.</p>
	<% elsif @order.okshop_at %>
                <p><%= @order.beneficiary.upcase %> <%=t('.shop_confirmed')%>.</p>
        <% else %>
                <p><strong><%=t('delivered')%></strong></p>

                        <div id="sticker-table">
			<ul>
                                <li>
                                        <ul>
                                            <li class="r"><%=t('.shop_delivery')%></li>
                                        </ul>
                                        <ul>
                                            <li class="l"><%= @order.okshop_at %></li>
                                        </ul>
                                </li>
                                <li>
                                        <ul>
                                            <li class="r"><%=t('.client_confirmation')%></li>
                                        </ul>
                                        <ul>
                                            <li class="l"><%= @order.okuser_at %></li>
                                        </ul>
                                </li>
			</ul>
                        </div>

        <% end %>
    <%#end%> <%# /@order.provider_type == "Facebook"%>
</div>