config/routes.rb
Hoopy::Application.routes.draw do

  get 'landing' => 'betatesters#new'
  get 'landing_ok' => 'betatesters#ok'

  get 'admin' => 'admin#index'
  controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy   # HM: Hoopy Login (Pend: juntar con Omniauth)
  end

  scope '(:locale)' do
   match "/signout" => "sessions#destroy", :as => :signout
   get 'welcome' => 'users#welcome'  # HM: Revisar!!
   get 'store' => 'store#index'
   get 'ready' => 'orders#ready'
   get 'selectfriend' => 'orders#selectfriend'
   post 'selectfriend' => 'sessions#setfriend' # Guarda el "friend" en el hash de la sesión
   get 'shops' => 'store#shops'
   get 'allies' => 'allies#index'
   get 'tos' => 'static#tos'
   get 'privacy' => 'static#privacy'
   get 'contact' => 'static#contact'
   get 'about' => 'static#about'
   post 'deliver' => 'orders#confirmdelivery'
   resources :enterprises do
        resources :products
   end
   resources :orders do
     member do
        get 'userpreview'
        get 'dealerpreview'
     end
   end
   resources :users
   resources :line_items
   resources :carts
   resources :products
   resources :betatesters
   get 'landing' => 'betatesters#new'
   get 'landing_ok' => 'betatesters#ok'
   post 'contactform' => 'betatesters#contactform'
   root :to => 'betatesters#new', :as => 'landing'
  end

 match "/auth/:provider/callback" => "sessions#create_omniauth"
 
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for?(:title) ? yield(:title) : "Huupy" %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
    <%= stylesheet_link_tag "bootstrap-responsive.min", :media => "all" %>
    <%= stylesheet_link_tag "isotope", :media => "all" %>
    <%= stylesheet_link_tag "font-awesome", :media => "all" %>
    <%= stylesheet_link_tag "hoopy", :media => "all" %>
    <%= stylesheet_link_tag "jquery-ui-1.8.24.custom", :media => "all" %>
    <%= javascript_include_tag "jquery-1.8.0.min" %>
    <%= javascript_include_tag "jquery-ui-1.8.24.custom.min" %>

    <%= csrf_meta_tags %>
    <link href="/favicon.ico" rel="shortcut icon">
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40477273-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <nav class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/" style="font-family:Berkshire Swash">Huupy</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if current_user %>
                 <% if current_user.type_id != 2 %>
                        <li><%= link_to t('.recvgifts'), welcome_path %></li>
                        <li><%= link_to t('.sentgifts'), selectfriend_path %></li>
                        <li><% link_to t('.viewall'), store_path %></li>
                 <% end %>
                 <% if current_user.type_id == 2 %>
                        <li><%= link_to t('.orders'), welcome_path %></li>
                        <li><%= link_to t('.manage_stock'), '' %></li>
                        <li><%= link_to t('.see_statistics'), '' %></li>
                        <li><%= link_to t('.help'), '' %></li>
                 <% end %>
                 <% if current_user.type_id == 1 %>
                        <li>ADMIN:</li>
                        <li><%= link_to 'Home', admin_path %></li>
                        <li><%= link_to 'Products', products_path %></li>
                        <li><%= link_to 'Users', users_path %></li>
                        <li><%= link_to 'Orders', orders_path %></li>
                        <li><%= link_to 'Enterprises', enterprises_path %></li>
                        <li><%= link_to 'Betatesters', betatesters_path %></li>
                 <% end %>
                        <li><%= link_to t('.logout'), signout_path %></li>
              <% else %>
                  <li><%= link_to t('.signin_with_hoopy'), login_path %></li>
                  <li><%= link_to t('.signin_with_twitter'), '/auth/twitter' %></li>
                  <li><% link_to t('.signin_with_facebook'), '/auth/facebook' %></li>
              <% end %>
            </ul><!-- .nav -->
          </div><!--/.nav-collapse -->
        </nav>
      </div><!-- .navbar-inner -->
    </header>

    <div class="wrapper">
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %> center" >
            <button data-dismiss="alert" class="close" type="button">x</button>
            <%= value %>
          </div>
        <% end %>
        <%= yield %>
      </div> <!-- /.container -->
      <div class="push"><!--//--></div>
    </div> <!-- /.wrapper -->

<footer id="footer">
 <div class="container">
  <hr>
    <p><%= link_to t('.tos'), tos_path %> &#8226; <%= link_to t('.privacy'), privacy_path %> &#8226; <%= link_to t('.contact'), contact_path %> 
       <br />
       &copy; Hugo's Huupy 2013</p>
    <small>
        <%= link_to "English", params.merge({:locale => :en}) %> •
        <%= link_to "Español", params.merge({:locale => :es}) %>
    </small>
 </div>
</footer>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <% javascript_include_tag "jquery-1.7.2.min" %>
    <%= javascript_include_tag "jquery.isotope.min" %>
    <%= javascript_include_tag "bootstrap" %>

<script>
$(function(){
  $('#catalog').isotope({
    // options
    itemSelector : '.item',
    layoutMode : 'cellsByRow',
    cellsByRow: {
      columnWidth: 180,
      rowHeight: 250
    }
  });
});
</script>

</body>
</html>

app/views/layouts/betatesters.html.erb
<%= yield %>